### ISSUE TITLE
Dialog boxes have tiny titlebar with no title text (Cinnamon DE)

### ISSUE THREAD

**Issue by Sadi58** [NicoHood/arc-theme#152] opened 2018-10-15 21:26 UTC
The title bar of dialog boxes in many apps is both very narrow and does not show the title text.
Linux Mint's default theme Mint-Y is based on the original Arc theme, and naturally it has the same issue. But some other themes like Numix and Greybird don't have this issue. 
**A quick list**
Firefox: File Open & Save both
Google Chrome: File Open & Save both
LibreOffice: File Open & Save both
medit: File Open & Save both
GIMP: File Open & Save both OK.
Thunderbird: Message Open & Save both, but not Preferences
Xed: File Open is OK but not File Save (screenshots below)

![selection_2018-10-16-00 21 29](https://user-images.githubusercontent.com/6375934/46979206-acc6f200-d0d9-11e8-8b95-66916f6ea4a9.jpg)

![selection_2018-10-16-00 20 27](https://user-images.githubusercontent.com/6375934/46979256-d4b65580-d0d9-11e8-9205-e542d88eb85a.jpg)

---------------------------------------------
Distribution: Linux Mint 19
Base distribution: Ubuntu 18.04
Desktop environment: Cinnamon 3.8.9
Arc version/commit: 20180716-1+201810081731
GTK+ 3 version: 3.22.30
Murrine engine version: 0.98.2
gnome-themes-extras version: 3.28
Installation method: package

**Comment by jnsh** [comment] 2018-10-19 07:29
As I said on the comments of another issue, I can't reproduce this in gnome-shell, so I'd imagine this is Cinnamon specific issue.

Unfortunately I don't think there are anyone actively maintaining the Arc cinnamon theme at the moment, so quite frankly this doesn't seem likely to get fixed here any time soon. If the same bug is present with Linux Mint's default theme, you may have better report this upstream to Mint developers, since they are developing the Cinnamon shell as well, and should have greater incentive for fixing the issue.

If they can figure out a fix, it can probably be backported to Arc theme with relative ease.

**Comment by Sadi58** [comment] 2018-10-19 09:55
Thanks, yes, this is a good idea!

**Comment by NicoHood** [comment] 2018-10-19 14:47
The mint devs forked arc theme, so they might be able to help you out with this. I do not understand why they dont contribute all the stuff back here and we are not working on color variants yet. Its the same torture like ubuntu/distribution forks.

**Comment by Sadi58** [comment] 2018-10-19 15:00
I will definitely let you know if they find a fix for this!

Unfortunately, this is a big problem in Linux world, too much duplication, framentation, lack of coordination, and eventually a lot of inefficiency. I'm not sure if this is the price of freedom that we have to pay...

For instance, they have a couple of things missing from the current Arc theme because they forked the original one - e.g. file manager tab being highlighted when you drag an item to it from another tab.

**Comment by Sadi58** [comment] 2018-10-21 15:20
I've just noticed another problem with those dialog boxes: some **missing widgets** as seen in the screenshot below - followed by another screenshot from the theme **Mint-Y-Yltra-Light** displaying those missing widgets like **Mint-Y** it's based on.
![selection_2018-10-21-18 03 10](https://user-images.githubusercontent.com/6375934/47268785-cfd02680-d55d-11e8-8ddf-bc33997f2b6d.jpg)
![selection_2018-10-21-18 05 45](https://user-images.githubusercontent.com/6375934/47268788-da8abb80-d55d-11e8-9f80-662acf25db85.jpg)

**Comment by Booteille** [comment] 2018-10-21 15:59
I have a similar issue with the latest version of arc-theme downloaded on the ppa [fossfreedom](https://launchpad.net/~fossfreedom/+archive/ubuntu/arc-gtk-theme-daily).

When I choose Arc-Dark (or any Arc variant) as my theme for controls, some buttons (like checkbox or close/minimize buttons of firefox) are hidden. They still work but I can't see them.
If I choose any other theme (like Mint-Y as an exemple), buttons show again.

Firefox with Arc-Dark :
![firefox_buttons_missing_arcdark](https://user-images.githubusercontent.com/2203721/47269201-04d27e00-d54a-11e8-964d-f5d3408596ca.png)
Firefox with Mint-Y Dark :
![firefox_buttons_minty](https://user-images.githubusercontent.com/2203721/47269203-056b1480-d54a-11e8-81e0-7f460ba76e62.png)
Checkbox with Arc-Dark :
![checkbox_missing_arcdark](https://user-images.githubusercontent.com/2203721/47269204-0603ab00-d54a-11e8-86b9-04bb49a15dca.png)
Checkbox with Mint-Y Dark :
![checkbox_minty](https://user-images.githubusercontent.com/2203721/47269205-0734d800-d54a-11e8-8467-fe8ffd6f584f.png)

**Comment by Sadi58** [comment] 2018-10-21 18:12
It's interesting, I don't have the problem reported above by @Booteille with **Firefox** (62.0.3 64-bit) window control buttons, but they are invisible in **Archive Manager** (and a couple of other gnome apps with the new **header bar** I guess).

**Comment by chewi** [comment] 2018-10-23 20:08
I believe this was broken in 550065724bb50cff953a067ce094fb63e4f5a7f6 (sorry) and fixed less than 24 hours later in 5444ac751f15ddcc7532ca06243def7c948ae6c1. Please retry.

**Comment by chewi** [comment] 2018-10-23 20:12
There was briefly a problem between 550065724bb50cff953a067ce094fb63e4f5a7f6 and 5444ac751f15ddcc7532ca06243def7c948ae6c1 that would have caused something like this and that's probably what the last comment refers to but this issue was opened before that.

**Comment by Booteille** [comment] 2018-10-24 07:46
My issue seems to be solved with the last update. (20181023-1+201810240002~ubuntu18.04.1)

**Comment by NicoHood** [comment] 2018-10-25 18:51
Can we close this now?

**Comment by Sadi58** [comment] 2018-10-25 21:03
It's not resolved. It's up to you to tag it "won't fix" and close. If I were in your shoes, I would keep it open until possibly a fix comes from Mint-Y team.

**Comment by NicoHood** [comment] 2018-10-27 17:35
The mint team does not care. They will not open any PR to fix things back here. You have to trigger them and ask if they can assist with help. I dont see any other solution. Otherwise we might consider to drop cinnamon support completely.

**Comment by Sadi58** [comment] 2018-10-28 09:33
They seem quite active here: https://github.com/linuxmint/mint-themes
Let's give them a little time...

**Comment by smurphos** [comment] 2018-12-03 06:33
This just needs a little tweak to the metacity-theme-3.xml for Cinnamon. I'm pretty sure the same bug is in Mate as-well - metacity-theme-2.xml for that one. Does any DE still use metacity-theme-1?

I'll double check Mate and make a fixing PR in the next day or two.

@NicoHood - if you'd like some help updating the Cinnamon.css to bring it in line for Cinnamon 4.x please let me know. I've got a few other jobs on my to do list first so it might be a week or so until I get time to get to it. 

For clarity I'm not part of Mint - just a user and contributor. Also a contributor to oomox, Materia and Adapta.

**Comment by fossfreedom** [comment] 2018-12-03 07:09
Yes please. We are definitely looking for people who are willing to finesse
their favourite desktop environment

**Comment by smurphos** [comment] 2018-12-09 10:47
@Sadi58 

Can you check your Window Manager settings. Specifically do you have 'Attach dialogs to their parent window' checked - that causes dialog windows to have no title in the titlebar with Arc as per the original design of the Metacity theme.

![screenshot-window-2018-12-09-104231](https://user-images.githubusercontent.com/29017677/49696254-6d7bc580-fb9f-11e8-8a6e-11efbd68cd2a.png)

Without it checked you get a smaller titlebar with a title with no close buttons in Arc. The PR I've just submitted gives them a normal size titlebar with a close button.

**Comment by Sadi58** [comment] 2018-12-09 10:59
@smurphos
You're right! Thanks!
I've unchecked it now and I even have a close button in GIMP unlike others ;-)

**Comment by smurphos** [comment] 2018-12-09 11:35
Cool - Now what I'm not sure of is whether the lack of a title for Attached dialogs (rather than unattached modal dialogs) on Arc and thus Mint-Y is a definitely a design decision or not. Other themes do have a title on attached windows. I'll need to play some spot the difference between Arc and some other themes as the obvious fix in Arc didn't work...

**Comment by JosephMcc** [comment] 2019-03-05 19:09
Hey guys. I stumbled across this completely by accident looking for something else. There seems to be some bad feelings toward Mint devs for not contributing back to you guys. Since I do nearly all maintenance on the mint themes that would be me you're pointing the finger at :) 

Unfortunately the problem here really comes down to time. I have a limited amount of time to work on this and trying to follow and help out even more projects just isn't in the cards. There is also the issue that the longer these two themes exist, the more they deviate from one another and the less relevant changes become to each other. Even the basic color schemes used in the two themes no longer match and this will continue to grow worse. I know you want to consider yourselves some kind of upstream from us but at this point I don't know that it's really very relevant. It has nothing to do with lack of caring.

**Comment by Sadi58** [comment] 2019-03-06 09:28
BTW, the issue is gone in **Mint-Y** theme now (with "Attach dialogs to their parent window" is checked in Settings/Windows).
Maybe you can figure out which change made this possible...

**Comment by smurphos** [comment] 2019-03-07 07:26
> BTW, the issue is gone in **Mint-Y** theme now (with "Attach dialogs to their parent window" is checked in Settings/Windows).
> Maybe you can figure out which change made this possible...

There's nothing to figure out - I submitted the PR to fix the issue in Mint-Y (which @JosephMcc reviewed IIRC)  and the equivalent PR here #174 is waiting to be merged subject to @NicoHood or @fossfreedom deciding it they want they want the other window decoration button modifications in the PR included or not.

**Comment by NicoHood** [comment] 2019-03-14 18:25
@fossfreedom We should just merge the PR, what do you think?

**Comment by fossfreedom** [comment] 2019-03-14 18:29
Agree. Merge and then everyone who has an interest can test further.

**Closed** 2019-03-14 18:32 UTC
Labels: Cinnamon, bug, help wanted
