### ISSUE TITLE
Blurry icons (close, minimize, maximize)

### ISSUE THREAD

**Issue by cazacugmihai** [NicoHood/arc-theme#77] opened 2018-05-09 21:34 UTC
![arc-darker](https://user-images.githubusercontent.com/89212/39840777-39dd7560-53e9-11e8-98cc-ba480ff5e3a2.png)

### Environment

```
OS: Ubuntu 18.04 LTS x86_64 
Kernel: 4.15.0-20-generic 
Resolution: 3840x2160 
DE: MATE 
WM: Compiz 
WM Theme: Arc-Darker 
Theme: Arc-Darker [GTK2/3] 
Icons: Arc [GTK2/3] 
GPU: Intel HD Graphics 530 

Arc-theme:
  Version: 20180114-1ubuntu1
  APT-Sources: http://mirrors.nav.ro/ubuntu bionic/universe amd64 Packages

gtk2-engines-murrine:
  Version: 0.98.2-2ubuntu1
  APT-Sources: http://mirrors.nav.ro/ubuntu bionic/main amd64 Packages

gnome-themes-standard:
  Version: 3.28-1ubuntu1
  APT-Sources: http://mirrors.nav.ro/ubuntu bionic/universe amd64 Packages

libgtk2.0-0:
  Installed: 2.24.32-1ubuntu1
  Version table:
 *** 2.24.32-1ubuntu1 500
        500 http://mirrors.nav.ro/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://mirrors.nav.ro/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by fossfreedom** [comment] 2018-05-09 21:40
Upstream issue. Duplicate of this. Also discussed on the linked adapta issue.

https://github.com/NicoHood/arc-theme/issues/52

**Closed by fossfreedom** 2018-05-09 21:40 UTC

**Comment by cazacugmihai** [comment] 2018-05-09 21:59
Thank you for pointing me to that issue! I didn't see it.
