### ISSUE TITLE
Arc Gnome Shell Theme is broken in Fedora 30

### ISSUE THREAD

**Issue by xoxys** [NicoHood/arc-theme#236] opened 2019-05-01 15:04 UTC
As you mentioned I've tried to install from source but issue persists. Installing the package on a fresh Fedora 30 installation does also not solve it.

See:
![Bildschirmfoto von 2019-05-01 16-58-11](https://user-images.githubusercontent.com/3391958/57023742-1ef4c380-6c33-11e9-935d-053a20d6c209.png)

**Comment by xoxys** [comment] 2019-05-01 15:16
Ok its not an issue in general but if you set the new display scaling feature from gnome 3.32 to e.g. 125% it breaks.

**Comment by D4v2z** [comment] 2019-05-01 17:52
The same thing happens to me, I found this but I did not find the solution...

https://github.com/NicoHood/arc-theme/issues/212

**Comment by twizmwazin** [comment] 2019-05-03 04:24
I am also having this issue, it shows up in the calendar, as well as the top right tray and any popovers, like pinentry. I currently have my laptop set simply to 200% scaling, however have previously had it plugged into a monitor with 125% scaling set.

**Comment by drakkar1969** [comment] 2019-05-05 16:25
This bug affects (at least) modal dialogs, panel menus, alt-tab switcher popup, workspace switcher popup, notifications and the looking glass dialog when display scaling is greater than 100%.
This seems to be caused by the border-image CSS property used to fake drop shadows: apparently gnome shell has a bug that incorrectly slices border images when using scaling that is not 100%.

A (hacky) fix is to replace `border-image: url(".........svg") 9 9 9 9;` with `border-image: url(".........svg") 16 16 16 16;` in `gnome-shell.css` for the following CSS selectors:
```
.popup-menu

.switcher-list

.workspace-switcher-container

.notification-banner, .notification-banner:hover, .notification-banner:focus

#LookingGlassDialog
```
The same change can be made for the `.modal-dialog` CSS selector, but there are still issues with button alignment in this case

Unfortunately, it seems that solving this issue completely would involve doing away with drop shadows altogether - until gnome shell solves this upstream

**Comment by D4v2z** [comment] 2019-05-07 09:12
In Overview, the box and the close button is also wrong, it is red when at 3.30 it is blue and it looks good.

3.30
![Captura de pantalla de 2019-05-07 11-09-04](https://user-images.githubusercontent.com/26611092/57287976-e46aab00-70b8-11e9-97b3-b4bb983c24c2.png)

**Comment by BenWoodworth** [comment] 2019-05-08 01:13
The clock text color turns blue after being clicked for me:
![image](https://user-images.githubusercontent.com/1829157/57342343-7c45b480-710c-11e9-85c0-3a00452c59c3.png)
![image](https://user-images.githubusercontent.com/1829157/57342352-88317680-710c-11e9-86d3-b0f6f35c152b.png)

I also have weird overview close buttons:
![image](https://user-images.githubusercontent.com/1829157/57342409-e78f8680-710c-11e9-9e26-55b425de8d67.png)

**Comment by twizmwazin** [comment] 2019-05-08 01:24
@BenWoodworth I believe that issue has already been fixed on master, see #212

**Comment by D4v2z** [comment] 2019-05-10 11:21
> @NicoHood The main issue here has not been fixed. This issue should not be closed. @BenWoodworth was referencing a separate issue.

Exactly, the issue has not been fixed.

**Comment by drakkar1969** [comment] 2019-05-12 11:19
Submitted a PR (#240) with a proposed fix for the display scaling issue.

Screenshots:

Modal dialog:
![modaldialog](https://user-images.githubusercontent.com/18715287/57581272-655ce480-74b5-11e9-9367-a734d6e25464.png)

Panel button dropdown menu:
![panelmenu1](https://user-images.githubusercontent.com/18715287/57581274-6aba2f00-74b5-11e9-9612-2874753fa519.png)
![panelmenu2](https://user-images.githubusercontent.com/18715287/57581275-6d1c8900-74b5-11e9-8280-c253886ca409.png)

OSD popup:
![osd](https://user-images.githubusercontent.com/18715287/57581276-7148a680-74b5-11e9-9f41-db06401d5212.png)

Notification:
![notification](https://user-images.githubusercontent.com/18715287/57581281-773e8780-74b5-11e9-91c1-79558d13f77c.png)

Window switcher:
![winswitcher](https://user-images.githubusercontent.com/18715287/57581284-802f5900-74b5-11e9-93c3-9b57762d1b84.png)

Workspace switcher:
![ws-switcher](https://user-images.githubusercontent.com/18715287/57581286-8291b300-74b5-11e9-9737-30eed89fd24a.png)

Looking glass:
![lg](https://user-images.githubusercontent.com/18715287/57581288-86253a00-74b5-11e9-84a7-9733a47ea726.png)

**Comment by twizmwazin** [comment] 2019-05-12 22:32
@drakkar1969 Thanks! I just built and tested locally, this fix seems to work on my machine!

**Closed** 2019-05-13 08:16 UTC
Labels: Gnome, help wanted
