### ISSUE TITLE
Blurry window controls button on HiDPI

### ISSUE THREAD

**Issue by ArchangeGabriel** [NicoHood/arc-theme#52] opened 2018-02-05 15:38 UTC
Nautilus capture below, on the left things are correct, but on the right buttons are blurry. This started recently, can’t tell if with 20180114 or something else since.
![capture du 2018-02-05 16-37-14](https://user-images.githubusercontent.com/490531/35813040-811fca98-0a8a-11e8-8924-103453b4a1f1.png)

### Details

- Distribution (with version): ArchLinux
- Desktop environment (with version): KDE Plasma
- Arc version/commit (don't put "latest"): 20180114
- GTK+ 3 version: 3.22
  - `gnome-themes-standard` version: 3.22
- Installation method (package or source): package

**Comment by fossfreedom** [comment] 2018-02-05 15:48
hmm - looks fine here on Ubuntu 17.10 - same GTK+3 version.

**Comment by ArchangeGabriel** [comment] 2018-02-05 16:30
HiDPI is definitively needed to get this issue.

**Comment by fossfreedom** [comment] 2018-02-05 16:46
@ArchangeGabriel its odd that you are using KDE with Nautilus.  What happens if you use a GTK+3 based desktop environment such as GNOME Shell?  This could be KDE specific.

**Comment by ArchangeGabriel** [comment] 2018-02-05 16:55
I don’t like GNOME Shell (and don’t have it installed, but will try when I have time) and don’t like KDE Apps (they have a terrible UI/UX, far too much controls, etc.), but I love GNOME Apps UI and I’m fine with Plasma (tried Cinnamon but too much issues, I’m waiting for the next version of Budgie based on Qt to give it a try, those guys are basically like me: love GNOME Apps, but not the Desktop). And I’m far from being the only person running GNOME Apps on a KDE Desktop, most people using Evince as PDF reader for instance.

**Comment by grg2rsr** [comment] 2018-02-10 10:25
It is not KDE specific - under Gnome-shell 3.26 here, Ubuntu 17.10, 4k hidpi screen and it looks exactly the same

**Comment by grg2rsr** [comment] 2018-02-10 10:41
This happens to me in chromium, when set to use the "GTK+" theme (instead of classic)
4k hidpi screen, Ubuntu 17.10, Gnome Shell 3.26

**Comment by grg2rsr** [comment] 2018-02-10 11:03
I can try. What are the steps needed than running the `render_assets.sh`? The results in the assets folder don't look any different.

**Comment by fossfreedom** [comment] 2018-02-10 11:08
Not sure with the dpi value. Suggest see if 240 or 360 make any difference.

**Comment by grg2rsr** [comment] 2018-02-10 12:02
well this did not work as intended. Just built, and the chromium icon still is blurry, but other icons got enlarged
![image](https://user-images.githubusercontent.com/9695626/36061933-927c1f36-0e62-11e8-83a8-4440442f952c.png)

**Comment by fossfreedom** [comment] 2018-02-10 12:39
Hmm. Is your issue only affecting chromium or all apps? Just wondering if it's a specific chromium issue with the way it handles hidpi

**Comment by grg2rsr** [comment] 2018-02-10 12:49
maybe, haven't found a different program that suffers from it yet, but also haven't checked all my apps ... The re-rendering in 360 dpi breaks all other icon sizes though, so the pull request should be rejected.

**Comment by ArchangeGabriel** [comment] 2018-02-12 12:25
For me it’s all apps. Chromium, Firefox, Nautilus… I haven’t had the time to try GNOME Shell yet.

**Comment by grg2rsr** [comment] 2018-02-12 13:02
@fossfreedom any idea what went wrong the the enlarged icon size after rendering them in a higher dpi setting? It seems like the process that places the png does not rescale it to fit whatever size it should get in the window, rather it places it centered irrespective of its size and thus gets clipped... did I forget to set something that informs some other process about the png pixel size?

**Comment by fossfreedom** [comment] 2018-02-12 13:15
@grg2rsr looking at other themes - the 2x icons are around 180 to 192 dpi - so 360 is perhaps too high and GTK+ does not render that high resolution - speculating.

Some themes pass through the results via optipng - some (like adapta) don't.

Other than that observation - I can't help much further - I don't have hidpi type equipment to view and experiment with.

**Comment by ArchangeGabriel** [comment] 2018-02-16 16:42
@fossfreedom You can emulate easily, just run `GDK_SCALE=2 <somegtkapp>`. You’ll see. And you can change 2 by 4 if you’re not convinced that there is an issue.

**Comment by fossfreedom** [comment] 2018-02-16 16:50
neat trick @ArchangeGabriel 

![untitled](https://user-images.githubusercontent.com/996240/36319006-7a4c63a4-1339-11e8-978e-82f1d4f83548.png)

but as you can see - all fine here.

**Comment by ArchangeGabriel** [comment] 2018-03-06 22:47
OK, so finally got the time to run some tests, and it appears that the issue is not DE specific nor theme specific, because for instance breeze-gtk is also affected. So at this point I believe that gtk3 is broken on Arch.

**Comment by fossfreedom** [comment] 2018-03-07 18:13
K. Thanks for the update. Since this is distro specific and not theme specific we will close it here. Cheers.

**Closed by fossfreedom** 2018-03-07 18:13 UTC

**Comment by ArchangeGabriel** [comment] 2018-03-07 18:17
This is believed to be the fix: https://gitlab.gnome.org/GNOME/gtk/commit/5aa939dc93a99736232b3a87511e8b78785c13a9

Testing it tonight.
